[package]
name = "php-rocksdb-rc"
version = "0.1.0"
edition = "2021"

[lib]
name = "libphprocksdb"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
ext-php-rs = "*"
rust-rocksdb = { version = "^0.26", features = ["multi-threaded-cf"] }