name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*' # Triggers on new version tags

jobs:
  build:
    runs-on: ubuntu-latest
    container: shivammathur/node:latest-${{ matrix.arch }}

    strategy:
      matrix:
        php-version: [8.1]
        arch: [amd64, i386, aarch64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gcc-multilib g++-multilib gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: php-config
          extensions: mbstring

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.arch }}-unknown-linux-gnu

      - name: Install Rust target
        run: rustup target add ${{ matrix.arch }}-unknown-linux-gnu

      - name: Build project
        run: cargo build --release --target ${{ matrix.arch }}-unknown-linux-gnu

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: libphprocksdb-${{ matrix.php-version }}-${{ matrix.arch }}
          path: target/${{ matrix.arch }}-unknown-linux-gnu/release/libphprocksdb.so

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: libphprocksdb-${{ matrix.php-version }}-${{ matrix.arch }}
          path: artifacts

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts
          asset_name: libphprocksdb-${{ matrix.php-version }}-${{ matrix.arch }}.so
          asset_content_type: application/octet-stream
